# Generated by Django 5.1.2 on 2024-11-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('screening_date', models.DateField()),
                ('screening_time', models.TimeField()),
                ('theater_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('available_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
