# Generated by Django 5.1.2 on 2024-11-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_seats',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
