# Generated by Django 5.1.2 on 2024-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
